#!/usr/bin/env bash

#
# Performs various lint-like checks.
#
# Warning: the checks are not sophisticated.
#

echo '--------------------------------------------------------------------------------'

# echo 'Check for capitalization in test descriptions ...'
# egrep -rn $'(describe|it)[ ]+[\'"][A-Z]' test/*.coffee

# echo 'Check for non-https protocols on urls in package.json ...'
# egrep $'[\'"]url[\'"][ ]*:' package.json | egrep -v 'https:'

# echo 'Check for occurrences of 'exception' (should use 'error' instead) ...'
# egrep -rin 'exception' src/*.coffee test/*.coffee

# echo 'Check for .only and .skip tests ...'
# egrep -rin '\.(only|skip) ' test/*.coffee

# echo 'Check Travis CI config file .travis.yml ...'
# QUIET=1 travis-lint

SOURCE_FILES="_build _lint _watch Gemfile package.json reset.css script.coffee style.scss Vagrantfile"

echo 'Check for tabs in source code files ...'
# egrep -rn '\t' src/*.coffee test/*.coffee Vagrantfile
egrep -rn '\t' $SOURCE_FILES

echo 'Check for trailing spaces in source files ...'
# egrep -rn ' $' src/*.coffee test/*.coffee Vagrantfile
egrep -rn ' $' $SOURCE_FILES

echo 'Check for git stashes ...'
git stash list

echo '--------------------------------------------------------------------------------'
