// Generated by CoffeeScript 1.7.1
(function() {
  var draggable, droppable, insert_section_targets, removeTargets;

  removeTargets = function() {
    return $(".target").remove();
  };

  droppable = {
    over: function() {
      return $(this).addClass("hilight-target");
    },
    out: function() {
      return $(this).removeClass("hilight-target");
    },
    drop: function() {
      return $(this).removeClass("target").removeClass("hilight-target").droppable("disable");
    }
  };

  draggable = {
    containment: ".lab",
    helper: function() {
      return $(this).clone().addClass("dragging");
    },
    stop: function() {
      return removeTargets();
    }
  };

  $(".toolbox header").draggable(draggable).draggable({
    start: function(event, ui) {
      var parents, targetFactory;
      targetFactory = $(this).clone().addClass("target");
      parents = $(".workbench, .workbench > section, .workbench article").filter(function() {
        return $("> header", this).length === 0;
      });
      return parents.each(function() {
        return $(this).prepend(targetFactory.clone().droppable(droppable));
      });
    }
  });

  $(".toolbox footer").draggable(draggable).draggable({
    start: function() {
      var parents, targetFactory;
      targetFactory = $(this).clone().addClass("target");
      parents = $(".workbench, .workbench > section").filter(function() {
        return $("> footer", this).length === 0;
      });
      return parents.each(function() {
        return $(this).append(targetFactory.clone().droppable(droppable));
      });
    }
  });

  $(".toolbox section").draggable(draggable).draggable({
    start: function() {
      return insert_section_targets($(this));
    }
  });

  $(".toolbox article").draggable(draggable).draggable({
    start: function() {
      var targetFactory;
      targetFactory = $(this).clone().addClass("target");
      return $(".workbench > section").each(function() {
        var footer, target;
        footer = $("footer", $(this))[0];
        target = targetFactory.clone().droppable(droppable);
        if (footer != null) {
          return target.insertBefore(footer);
        } else {
          return target.appendTo($(this));
        }
      });
    }
  });

  insert_section_targets = function(source) {
    var footer, header, target, targetFactory;
    targetFactory = source.clone().addClass("target");
    header = $(".workbench > header")[0];
    footer = $(".workbench > footer")[0];
    if ($(".workbench > .left-sidebar").length === 0) {
      target = targetFactory.clone().addClass("left-sidebar").droppable(droppable);
      if (header != null) {
        target.insertAfter(header);
      } else {
        target.prependTo($(".workbench"));
      }
    }
    if ($(".workbench > .right-sidebar").length === 0) {
      target = targetFactory.clone().addClass("right-sidebar").droppable(droppable);
      if (header != null) {
        target.insertAfter(header);
      } else {
        target.prependTo($(".workbench"));
      }
    }
    if ($(".workbench > .main").length === 0) {
      target = targetFactory.clone().addClass("main").droppable(droppable);
      if (footer != null) {
        return target.insertBefore(footer);
      } else {
        return target.appendTo($(".workbench"));
      }
    }
  };

}).call(this);
