// Generated by CoffeeScript 1.7.1
(function() {
  var draggable, drop, droppable;

  draggable = {
    containment: ".lab",
    revert: true,
    revertDuration: 200,
    start: function() {
      $(this).addClass("dragging");
      return $(".target").css("visibility", "visible");
    },
    stop: function() {
      $(this).removeClass("dragging");
      return $(".target").css("visibility", "hidden");
    }
  };

  drop = function(event, ui) {
    $(ui.draggable.data("html")).appendTo(this);
    return $(this).removeClass("drop-target");
  };

  droppable = {
    greedy: true,
    over: function() {
      return $(this).addClass("drop-target");
    },
    out: function() {
      return $(this).removeClass("drop-target");
    },
    drop: drop
  };

  $(".toolbox header").data({
    html: "<header></header>"
  });

  $(".toolbox section").data({
    html: "<section></section>"
  });

  $(".toolbox header, .toolbox section").draggable(draggable);

  $(".workbench").droppable(droppable);

}).call(this);
